version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip && mv terraform /usr/local/bin/
      - pip3 install checkov
      
  pre_build:
    commands:
      - echo "Starting AWS CodePipeline..."
      
  build:
    commands:
      - |
        # Download and execute centralized pipeline script
        curl -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3.raw" \
          -o pipeline.sh \
          https://api.github.com/repos/vpapakir/iac-pipeline-templates/contents/aws/scripts/traffic-light-pipeline.sh
        
        chmod +x pipeline.sh
        
        # Execute with parameters
        ./pipeline.sh \
          --ci-tool "aws_pipeline" \
          --default-cloud-provider "aws" \
          --terraform-cloud-token "$TF_CLOUD_TOKEN" \
          --github-token "$GITHUB_TOKEN" \
          --commit-sha "$CODEBUILD_RESOLVED_SOURCE_VERSION" \
          --branch-ref "$CODEBUILD_WEBHOOK_HEAD_REF" \
          --repo-name "vpapakir/iac-molecule-compute"
        
  post_build:
    commands:
      - echo "AWS CodePipeline completed"

artifacts:
  files:
    - '**/*'