version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform and tools..."
      - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      - pip3 install checkov
      
  pre_build:
    commands:
      - echo "Starting AWS CodePipeline build..."
      - echo "Branch - $CODEBUILD_WEBHOOK_HEAD_REF"
      
  build:
    commands:
      - |
        # Configure Terraform Cloud
        mkdir -p ~/.terraform.d
        echo "credentials \"app.terraform.io\" { token = \"$TF_CLOUD_TOKEN\" }" > ~/.terraform.d/credentials.tfrc.json
        
        # Plan and Test stages
        cd examples/aws-example
        terraform init && terraform plan && terraform validate
        cd ../..
        
        cd iac/terraform/aws
        terraform init && terraform fmt -check && terraform validate
        checkov -d . --framework terraform
        cd ../../..
        
        # Check if this is a feature branch (create PR)
        if [[ "$CODEBUILD_WEBHOOK_HEAD_REF" != "refs/heads/main" ]] && [[ "$CODEBUILD_WEBHOOK_HEAD_REF" != "" ]]; then
          echo "Feature branch detected - creating PR"
          
          # Install GitHub CLI
          yum update -y && yum install -y git
          curl -fsSL https://github.com/cli/cli/releases/download/v2.40.1/gh_2.40.1_linux_amd64.tar.gz -o gh.tar.gz
          tar -xzf gh.tar.gz && mv gh_2.40.1_linux_amd64/bin/gh /usr/local/bin/
          
          # Create PR via API
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/vpapakir/iac-molecule-compute/pulls \
            -d "{
              \"title\": \"[aws] Release: Module updates\",
              \"body\": \"Automated PR - merge with APPROVED PATCH [aws]\",
              \"head\": \"development\",
              \"base\": \"main\"
            }"
            
        # Check if this is main branch (publish release)
        elif [[ "$CODEBUILD_WEBHOOK_HEAD_REF" == "refs/heads/main" ]]; then
          echo "Main branch detected - publishing release"
          
          # Setup git
          git config --global user.email "pipeline@company.com"
          git config --global user.name "AWS CodeBuild"
          
          # Get version
          git fetch --tags
          LATEST_TAG=$(git tag -l "v*" | sort -V | tail -n1)
          if [ -z "$LATEST_TAG" ]; then
            VERSION="0.0.1"
          else
            CURRENT_VERSION=${LATEST_TAG#v}
            IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
            VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          fi
          
          # Create and push tag
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git remote set-url origin https://$GITHUB_TOKEN@github.com/vpapakir/iac-molecule-compute.git
          git push origin "v$VERSION"
          
          echo "Published version: v$VERSION"
        else
          echo "Manual build - skipping PR/release"
        fi
        
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'