AWSTemplateFormatVersion: '2010-09-09'
Description: 'CodePipeline for iac-molecule-compute plan-test-release workflow'

Parameters:
  GitHubRepo:
    Type: String
    Default: 'iac-molecule-compute'
    Description: 'GitHub repository name'
  
  GitHubOwner:
    Type: String
    Description: 'GitHub repository owner'
  
  GitHubToken:
    Type: String
    NoEcho: true
    Description: 'GitHub personal access token'
  
  GitHubBranch:
    Type: String
    Default: 'main'
    Description: 'GitHub branch to monitor (main or master)'
    AllowedValues:
      - main
      - master
  
  TerraformCloudToken:
    Type: String
    NoEcho: true
    Description: 'Terraform Cloud API token'
  
  TemplatesVersion:
    Type: String
    Default: 'v0.0.1'
    Description: 'Version of iac-pipeline-templates to use'

Resources:
  # S3 Bucket for pipeline artifacts
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-pipeline-artifacts'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # IAM Role for CodePipeline
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource: !Sub '${ArtifactsBucket}/*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: !Ref ArtifactsBucket
              - Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource: 
                  - !GetAtt CommitCheckBuild.Arn
                  - !GetAtt PlanBuild.Arn
                  - !GetAtt TestBuild.Arn
                  - !GetAtt CreatePRBuild.Arn
                  - !GetAtt ReleaseBuild.Arn

  # IAM Role for CodeBuild
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource: !Sub '${ArtifactsBucket}/*'

  # CodeBuild Project for Commit Check
  CommitCheckBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${AWS::StackName}-commit-check'
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - |
                  COMMIT_MSG=$(git log -1 --pretty=%B)
                  echo "Commit message: $COMMIT_MSG"
                  
                  # Check if this is AWS pipeline or default (no prefix)
                  if [[ "$COMMIT_MSG" == *"[aws]"* ]] || [[ "$COMMIT_MSG" != *"[ado]"* && "$COMMIT_MSG" != *"[gh]"* ]]; then
                    echo "✓ Pipeline should run for AWS"
                    exit 0
                  else
                    echo "✗ Pipeline should not run for AWS - commit message: $COMMIT_MSG"
                    exit 1
                  fi

  # CodeBuild Project for Plan
  PlanBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${AWS::StackName}-plan'
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        EnvironmentVariables:
          - Name: TF_CLOUD_TOKEN
            Value: !Ref TerraformCloudToken
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                python: 3.8
              commands:
                - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
                - unzip terraform_1.6.0_linux_amd64.zip
                - mv terraform /usr/local/bin/
                - terraform --version
            pre_build:
              commands:
                - echo "Configuring Terraform Cloud authentication..."
                - mkdir -p ~/.terraform.d
                - echo "credentials \"app.terraform.io\" { token = \"$TF_CLOUD_TOKEN\" }" > ~/.terraform.d/credentials.tfrc.json
            build:
              commands:
                - echo "Testing module consumption patterns..."
                - cd examples/aws-example
                - terraform init
                - terraform plan
                - cd ../azure-example  
                - terraform init
                - terraform plan
                - echo "✓ Plan stage completed successfully"

  # CodeBuild Project for Test
  TestBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${AWS::StackName}-test'
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                python: 3.8
              commands:
                - pip install checkov
                - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
                - unzip terraform_1.6.0_linux_amd64.zip
                - mv terraform /usr/local/bin/
            build:
              commands:
                - echo "Running security scanning and linting..."
                - cd iac/terraform/aws
                - terraform fmt -check
                - terraform validate
                - checkov -f . --framework terraform --quiet
                - cd ../azure
                - terraform fmt -check  
                - terraform validate
                - checkov -f . --framework terraform --quiet
                - cd ../civo
                - terraform fmt -check
                - terraform validate
                - checkov -f . --framework terraform --quiet
                - cd ../oci
                - terraform fmt -check
                - terraform validate
                - checkov -f . --framework terraform --quiet
                - echo "✓ All security and linting tests passed"

  # CodeBuild Project for Create PR
  CreatePRBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${AWS::StackName}-create-pr'
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        EnvironmentVariables:
          - Name: GITHUB_TOKEN
            Value: !Ref GitHubToken
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - echo "Installing GitHub CLI..."
                - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
                - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
                - apt update && apt install gh -y
            build:
              commands:
                - echo "Creating pull request..."
                - |
                  # Only run if [release] flag is present and not on main/master
                  COMMIT_MSG=$(git log -1 --pretty=%B)
                  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
                  
                  if [[ "$COMMIT_MSG" != *"[release]"* ]]; then
                    echo "No [release] flag found, skipping PR creation"
                    exit 0
                  fi
                  
                  if [[ "$CURRENT_BRANCH" == "main" ]] || [[ "$CURRENT_BRANCH" == "master" ]]; then
                    echo "Already on main/master branch, skipping PR creation"
                    exit 0
                  fi
                  
                  # Configure git
                  git config --global user.email "pipeline@company.com"
                  git config --global user.name "AWS CodeBuild"
                  
                  # Authenticate with GitHub
                  echo "$GITHUB_TOKEN" | gh auth login --with-token
                  
                  # Determine target branch
                  if git show-ref --verify --quiet refs/remotes/origin/main; then
                    TARGET_BRANCH="main"
                  else
                    TARGET_BRANCH="master"
                  fi
                  echo "Target branch: $TARGET_BRANCH"
                  
                  # Create PR
                  PR_TITLE="Release: $(echo "$COMMIT_MSG" | head -n1 | sed 's/\[.*\]//g' | xargs)"
                  
                  gh pr create \
                    --title "$PR_TITLE" \
                    --body "Automated PR created by AWS CodePipeline

                  Commit: $COMMIT_MSG

                  Ready for review and release approval." \
                    --base "$TARGET_BRANCH" \
                    --head "$CURRENT_BRANCH"
                  
                  echo "✓ Pull request created successfully"

  # CodeBuild Project for Release
  ReleaseBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${AWS::StackName}-release'
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        EnvironmentVariables:
          - Name: TF_CLOUD_TOKEN
            Value: !Ref TerraformCloudToken
          - Name: GITHUB_TOKEN
            Value: !Ref GitHubToken
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - echo "Installing Git..."
                - yum install -y git
            build:
              commands:
                - echo "Publishing modules to Terraform Cloud..."
                - |
                  # Only run on main/master branch
                  CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
                  if [[ "$CURRENT_BRANCH" != "main" ]] && [[ "$CURRENT_BRANCH" != "master" ]]; then
                    echo "Not on main/master branch, skipping release"
                    exit 0
                  fi
                  
                  # Configure git with GitHub token for authentication
                  git config --global user.email "pipeline@company.com"
                  git config --global user.name "AWS CodeBuild"
                  git remote set-url origin https://$GITHUB_TOKEN@github.com/$CODEBUILD_SOURCE_REPO_URL
                  
                  # Get the latest version from git tags
                  echo "Fetching latest version from git tags..."
                  git fetch --tags
                  LATEST_TAG=$(git tag -l "v*" | sort -V | tail -n1)
                  
                  if [ -z "$LATEST_TAG" ]; then
                    # No previous tags, start with 0.0.1
                    CURRENT_MAJOR=0
                    CURRENT_MINOR=0
                    CURRENT_PATCH=1
                    echo "No previous tags found, starting with 0.0.1"
                  else
                    # Parse current version
                    CURRENT_VERSION=${LATEST_TAG#v}
                    CURRENT_MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
                    CURRENT_MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
                    CURRENT_PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
                    echo "Current version: $CURRENT_VERSION (Major: $CURRENT_MAJOR, Minor: $CURRENT_MINOR, Patch: $CURRENT_PATCH)"
                  fi
                  
                  # Get PR approval message to determine version bump
                  echo "Checking PR approval message for version bump type..."
                  
                  # Get the merge commit message which contains PR info
                  MERGE_COMMIT_MSG="$(git log -1 --pretty=%B)"
                  echo "Merge commit message: $MERGE_COMMIT_MSG"
                  
                  # Determine version bump based on approval message
                  if echo "$MERGE_COMMIT_MSG" | grep -i "APPROVED MAJOR" > /dev/null; then
                    NEW_MAJOR=$((CURRENT_MAJOR + 1))
                    NEW_MINOR=0
                    NEW_PATCH=0
                    BUMP_TYPE="MAJOR"
                  elif echo "$MERGE_COMMIT_MSG" | grep -i "APPROVED MINOR" > /dev/null; then
                    NEW_MAJOR=$CURRENT_MAJOR
                    NEW_MINOR=$((CURRENT_MINOR + 1))
                    NEW_PATCH=0
                    BUMP_TYPE="MINOR"
                  else
                    # Default to PATCH if no specific approval message or "APPROVED PATCH"
                    NEW_MAJOR=$CURRENT_MAJOR
                    NEW_MINOR=$CURRENT_MINOR
                    NEW_PATCH=$((CURRENT_PATCH + 1))
                    BUMP_TYPE="PATCH"
                  fi
                  
                  VERSION="$NEW_MAJOR.$NEW_MINOR.$NEW_PATCH"
                  echo "Version bump type: $BUMP_TYPE"
                  echo "Publishing version: $VERSION"
                  
                  # Create git tag for this version
                  git tag -a "v$VERSION" -m "Automated release v$VERSION"
                  git push origin "v$VERSION"
                  
                  echo "✓ Modules published with version: v$VERSION"

  # CodePipeline
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${AWS::StackName}-pipeline'
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactsBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: SourceOutput

        - Name: CommitCheck
          Actions:
            - Name: CheckCommitMessage
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CommitCheckBuild
              InputArtifacts:
                - Name: SourceOutput

        - Name: Plan
          Actions:
            - Name: TerraformPlan
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref PlanBuild
              InputArtifacts:
                - Name: SourceOutput

        - Name: Test
          Actions:
            - Name: SecurityAndLinting
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref TestBuild
              InputArtifacts:
                - Name: SourceOutput

        - Name: CreatePR
          Actions:
            - Name: CreatePullRequest
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CreatePRBuild
              InputArtifacts:
                - Name: SourceOutput

        - Name: Release
          Actions:
            - Name: PublishModules
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref ReleaseBuild
              InputArtifacts:
                - Name: SourceOutput

Outputs:
  PipelineName:
    Description: 'Name of the CodePipeline'
    Value: !Ref Pipeline
  
  ArtifactsBucket:
    Description: 'S3 bucket for pipeline artifacts'
    Value: !Ref ArtifactsBucket