jobs:
- job: CreatePullRequest
  displayName: 'Create Pull Request to Main'
  steps:
  - script: |
      echo "Configuring Azure DevOps CLI..."
      az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject)
      
      echo "Creating pull request to main branch..."
      
      # Get current branch name from Azure DevOps variables
      CURRENT_BRANCH="$(Build.SourceBranchName)"
      echo "Current branch: $CURRENT_BRANCH"
      
      # Get repository name from Azure DevOps variables
      REPO_NAME="$(Build.Repository.Name)"
      echo "Repository: $REPO_NAME"
      
      # Determine target branch (main or master)
      if git show-ref --verify --quiet refs/remotes/origin/main; then
        TARGET_BRANCH="main"
      else
        TARGET_BRANCH="master"
      fi
      echo "Target branch: $TARGET_BRANCH"
      
      # Create PR title and body
      COMMIT_MSG="$(Build.SourceVersionMessage)"
      PR_TITLE="Release: $COMMIT_MSG"
      PR_BODY="Automated release PR created from commit: $(Build.SourceVersion)

      Changes:
      - Module updates ready for release
      - All tests passed
      - Security scans completed
      
      This PR was automatically created because [release] was found in the commit message."
      
      # Create PR using Azure DevOps REST API
      az repos pr create \
        --repository "$REPO_NAME" \
        --title "$PR_TITLE" \
        --description "$PR_BODY" \
        --source-branch "$CURRENT_BRANCH" \
        --target-branch "$TARGET_BRANCH" \
        --auto-complete true \
        --delete-source-branch false
      
      echo "Pull request created successfully"
    displayName: 'Create Pull Request'
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)