parameters:
- name: terraformVersion
  type: string
  default: '1.6.0'
- name: modulePaths
  type: object
  default: ['iac/terraform/aws', 'iac/terraform/azure']

jobs:
- job: LintAndScan
  displayName: 'Code Quality and Security'
  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: ${{ parameters.terraformVersion }}

  - script: |
      echo "Configuring Terraform Cloud authentication..."
      echo "credentials \"app.terraform.io\" {" > ~/.terraformrc
      echo "  token = \"$(apiKey)\"" >> ~/.terraformrc
      echo "}" >> ~/.terraformrc
    displayName: 'Configure Terraform Cloud'
    env:
      TF_CLOUD_TOKEN: $(apiKey)

  - script: |
      pip install checkov
    displayName: 'Install Security Tools'

  - ${{ each path in parameters.modulePaths }}:
    - script: |
        echo "Initializing and linting ${{ path }}: $(pwd)"
        cd ${{ path }}
        terraform init
        terraform fmt -check
        terraform validate
      displayName: 'Terraform Lint - ${{ path }}'
      env:
        TF_CLOUD_TOKEN: $(apiKey)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

  - ${{ each path in parameters.modulePaths }}:
    - script: |
        echo "Scanning ${{ path }}: $(pwd)"
        cd ${{ path }}
        echo "Files in directory:"
        ls -la *.tf
        checkov -d . --framework terraform --quiet
      displayName: 'Security Scan - ${{ path }}'