parameters:
- name: terraformVersion
  type: string
  default: '1.6.0'
- name: modulePaths
  type: object
  default: ['iac/terraform/aws', 'iac/terraform/azure']

jobs:
- job: LintAndScan
  displayName: 'Code Quality and Security'
  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: ${{ parameters.terraformVersion }}

  - script: |
      pip install checkov
    displayName: 'Install Security Tools'

  - ${{ each path in parameters.modulePaths }}:
    - script: |
        echo "Linting ${{ path }}: $(pwd)"
        cd ${{ path }}
        terraform fmt -check
        terraform validate
      displayName: 'Terraform Lint - ${{ path }}'

  - ${{ each path in parameters.modulePaths }}:
    - script: |
        echo "Scanning ${{ path }}: $(pwd)"
        cd ${{ path }}
        checkov -f . --framework terraform
      displayName: 'Security Scan - ${{ path }}'