jobs:
- job: PublishModules
  displayName: 'Publish to Terraform Registry'
  steps:
  - script: |
      echo "Publishing modules to Terraform Cloud..."
      
      # Generate version based on build number and commit
      VERSION="0.1.${BUILD_BUILDNUMBER}-$(echo ${BUILD_SOURCEVERSION} | cut -c1-7)"
      echo "Publishing version: $VERSION"
      
      # Create git tag for this version
      git config user.email "pipeline@company.com"
      git config user.name "Azure Pipeline"
      git tag -a "v$VERSION" -m "Automated release v$VERSION"
      git push origin "v$VERSION"
      
      echo "Modules published with version: v$VERSION"
      echo "##vso[task.setvariable variable=PublishedVersion]v$VERSION"
    displayName: 'Publish Modules'
    env:
      TF_CLOUD_TOKEN: $(apiKey)