parameters:
- name: terraformVersion
  type: string
  default: '1.6.0'
- name: examplePaths
  type: object
  default: ['examples/azure-example', 'examples/aws-example']

jobs:
- job: TerraformPlan
  displayName: 'Run Terraform Plan'
  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: ${{ parameters.terraformVersion }}

  - script: |
      echo "Configuring Terraform Cloud authentication..."
      echo "credentials \"app.terraform.io\" {" > ~/.terraformrc
      echo "  token = \"$(apiKey)\"" >> ~/.terraformrc
      echo "}" >> ~/.terraformrc
      
      echo "Initializing Terraform examples..."
      ${{ each path in parameters.examplePaths }}:
      cd ${{ path }}
      echo "Initializing ${{ path }}: $(pwd)"
      terraform init
      cd - > /dev/null
      ${{ end }}
    displayName: 'Terraform Init'
    env:
      TF_CLOUD_TOKEN: $(apiKey)
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

  - script: |
      echo "Running Terraform plan..."
      ${{ each path in parameters.examplePaths }}:
      cd ${{ path }}
      echo "Planning ${{ path }}: $(pwd)"
      terraform plan
      cd - > /dev/null
      ${{ end }}
    displayName: 'Terraform Plan'
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)