parameters:
- name: terraformVersion
  type: string
  default: '1.6.0'
- name: examplePaths
  type: object
  default: ['examples/azure-example', 'examples/aws-example']

jobs:
- job: TerraformPlan
  displayName: 'Run Terraform Plan'
  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: ${{ parameters.terraformVersion }}

  - script: |
      echo "Configuring Terraform Cloud authentication..."
      echo "credentials \"app.terraform.io\" {" > ~/.terraformrc
      echo "  token = \"$(apiKey)\"" >> ~/.terraformrc
      echo "}" >> ~/.terraformrc
    displayName: 'Configure Terraform Cloud'
    env:
      TF_CLOUD_TOKEN: $(apiKey)

  - ${{ each path in parameters.examplePaths }}:
    - script: |
        echo "Initializing ${{ path }}: $(pwd)"
        cd ${{ path }}
        terraform init
      displayName: 'Terraform Init - ${{ path }}'
      env:
        TF_CLOUD_TOKEN: $(apiKey)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

  - ${{ each path in parameters.examplePaths }}:
    - script: |
        echo "Planning ${{ path }}: $(pwd)"
        cd ${{ path }}
        terraform plan
      displayName: 'Terraform Plan - ${{ path }}'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)