parameters:
- name: terraformVersion
  type: string
  default: '1.6.0'
- name: modulePaths
  type: object
  default: ['iac/terraform/aws', 'iac/terraform/azure']

jobs:
- job: LintAndScan
  displayName: 'Code Quality and Security'
  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: ${{ parameters.terraformVersion }}

  - script: |
      pip install checkov
    displayName: 'Install Security Tools'

  - script: |
      echo "Running Terraform format check and validation..."
      ${{ each path in parameters.modulePaths }}:
      cd ${{ path }}
      echo "Linting ${{ path }}: $(pwd)"
      terraform fmt -check
      terraform validate
      cd - > /dev/null
      ${{ end }}
    displayName: 'Terraform Lint'

  - script: |
      echo "Running security scan with Checkov..."
      ${{ each path in parameters.modulePaths }}:
      cd ${{ path }}
      echo "Scanning ${{ path }}: $(pwd)"
      checkov -f . --framework terraform
      cd - > /dev/null
      ${{ end }}
    displayName: 'Security Scan'