parameters:
- name: condition
  type: string

stages:
- stage: CreatePR
  displayName: 'Create Release PR'
  dependsOn: Test
  condition: ${{ parameters.condition }}
  jobs:
  - template: ../jobs/create-pr.yml