parameters:
- name: condition
  type: string
- name: terraformVersion
  type: string
  default: '1.6.0'
- name: examplePaths
  type: object
  default: ['examples/azure-example']

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  condition: ${{ parameters.condition }}
  variables:
  - group: terraform
  - group: shared
  jobs:
  - template: ../jobs/terraform-plan.yml
    parameters:
      terraformVersion: ${{ parameters.terraformVersion }}
      examplePaths: ${{ parameters.examplePaths }}