parameters:
- name: condition
  type: string

stages:
- stage: Release
  displayName: 'Release Modules'
  dependsOn: Test
  condition: ${{ parameters.condition }}
  variables:
  - group: terraform
  - group: shared
  jobs:
  - template: ../jobs/terraform-release.yml