parameters:
- name: terraformVersion
  type: string
  default: '1.6.0'
- name: modulePaths
  type: object
  default: ['iac/terraform/aws', 'iac/terraform/azure']

stages:
- stage: Test
  displayName: 'Lint and Security Scan'
  dependsOn: Plan
  variables:
  - group: terraform
  - group: shared
  jobs:
  - template: ../jobs/terraform-test.yml
    parameters:
      terraformVersion: ${{ parameters.terraformVersion }}
      modulePaths: ${{ parameters.modulePaths }}