trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - README.md
      - .github/*
      - .aws/*
      - .oci/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.6.0'
  shouldRun: $[or(contains(variables['Build.SourceVersionMessage'], '[ado]'), not(or(contains(variables['Build.SourceVersionMessage'], '[gh]'), contains(variables['Build.SourceVersionMessage'], '[aws]'), contains(variables['Build.SourceVersionMessage'], '[oci]'))))]
  shouldCreatePR: $[and(contains(variables['Build.SourceVersionMessage'], '[release]'), ne(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.SourceBranch'], 'refs/heads/master'))]
  shouldRelease: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))]

resources:
  repositories:
  - repository: templates
    type: github
    name: vpapakir/iac-pipeline-templates
    ref: refs/tags/v0.0.1
    endpoint: github-iac

stages:
- template: azure-devops/stages/commit-check.yml@templates
  parameters:
    condition: true
    platformPrefix: '[ado]'
    excludePrefixes: ['[gh]', '[aws]', '[oci]']

- template: azure-devops/stages/plan.yml@templates
  parameters:
    condition: $[eq(variables.shouldRun, true)]
    terraformVersion: $(terraformVersion)
    examplePaths: 
      - 'examples/azure-example'
      - 'examples/aws-example'

- template: azure-devops/stages/test.yml@templates
  parameters:
    condition: $[eq(variables.shouldRun, true)]
    terraformVersion: $(terraformVersion)
    modulePaths:
      - 'iac/terraform/aws'
      - 'iac/terraform/azure'
      - 'iac/terraform/civo'
      - 'iac/terraform/oci'

- template: azure-devops/stages/create-pr.yml@templates
  parameters:
    condition: $[and(succeeded(), eq(variables.shouldCreatePR, true))]

- template: azure-devops/stages/release.yml@templates
  parameters:
    condition: $[and(succeeded(), eq(variables.shouldRelease, true))]