trigger:
  branches:
    include:
      - '*'

resources:
  repositories:
  - repository: templates
    type: github
    name: vpapakir/iac-pipeline-templates
    ref: refs/tags/v0.0.6
    endpoint: github-iac

variables:
- group: terraform
- group: shared
- name: ciTool
  value: 'ado'
- name: defaultCloudProvider
  value: 'azure'

stages:
- template: azure/stages/traffic-light-pipeline.yml@templates
  parameters:
    ciTool: $(ciTool)
    defaultCloudProvider: $(defaultCloudProvider)
    terraformCloudToken: $(apiKey)
    githubToken: $(GITHUB_TOKEN)
    azureCredentials:
      clientId: $(ARM_CLIENT_ID)
      clientSecret: $(ARM_CLIENT_SECRET)
      subscriptionId: $(ARM_SUBSCRIPTION_ID)
      tenantId: $(ARM_TENANT_ID)