trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - README.md
      - .github/*
      - .aws/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.6.0'
  shouldRun: $[or(contains(variables['Build.SourceVersionMessage'], '[ado]'), not(or(contains(variables['Build.SourceVersionMessage'], '[gh]'), contains(variables['Build.SourceVersionMessage'], '[aws]'))))]

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  condition: eq(variables.shouldRun, true)
  variables:
  - group: terraform
  - group: shared
  jobs:
  - job: TerraformPlan
    displayName: 'Run Terraform Plan'
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: $(terraformVersion)

    - script: |
        echo "Configuring Terraform Cloud authentication..."
        echo "credentials \"app.terraform.io\" {" > ~/.terraformrc
        echo "  token = \"$(apiKey)\"" >> ~/.terraformrc
        echo "}" >> ~/.terraformrc
        
        echo "Configuring Azure authentication..."
        export ARM_CLIENT_ID="$(ARM_CLIENT_ID)"
        export ARM_CLIENT_SECRET="$(ARM_CLIENT_SECRET)"
        export ARM_SUBSCRIPTION_ID="$(ARM_SUBSCRIPTION_ID)"
        export ARM_TENANT_ID="$(ARM_TENANT_ID)"
        
        echo "Initializing Terraform examples..."
        cd examples/azure-example
        echo "Azure example directory: $(pwd)"
        ls -la
        terraform init
        cd ../aws-example
        echo "AWS example directory: $(pwd)"
        ls -la
        terraform init
        cd ../..
      displayName: 'Terraform Init'
      env:
        TF_CLOUD_TOKEN: $(apiKey)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

    - script: |
        echo "Running Terraform plan for Azure example..."
        cd examples/azure-example
        terraform plan
        cd ../aws-example
        echo "Running Terraform plan for AWS example..."
        terraform plan
        cd ../..
      displayName: 'Terraform Plan'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)

- stage: Test
  displayName: 'Lint and Security Scan'
  dependsOn: Plan
  jobs:
  - job: LintAndScan
    displayName: 'Code Quality and Security'
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: $(terraformVersion)

    - script: |
        pip install checkov
      displayName: 'Install Security Tools'

    - script: |
        echo "Running Terraform format check..."
        cd iac/terraform/aws
        terraform fmt -check
        terraform validate
        cd ../azure
        terraform fmt -check
        terraform validate
        cd ../../..
      displayName: 'Terraform Lint'

    - script: |
        echo "Running security scan with Checkov..."
        cd iac/terraform/aws
        checkov -f . --framework terraform
        cd ../azure
        checkov -f . --framework terraform
        cd ../../..
      displayName: 'Security Scan'

- stage: Release
  displayName: 'Release Modules'
  dependsOn: Test
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
  variables:
  - group: terraform
  jobs:
  - job: PublishModules
    displayName: 'Publish to Terraform Registry'
    steps:
    - script: |
        echo "Publishing modules to Terraform Cloud..."
        
        # Generate version based on build number and commit
        VERSION="0.1.${BUILD_BUILDNUMBER}-$(echo ${BUILD_SOURCEVERSION} | cut -c1-7)"
        echo "Publishing version: $VERSION"
        
        # Create git tag for this version
        git config user.email "pipeline@company.com"
        git config user.name "Azure Pipeline"
        git tag -a "v$VERSION" -m "Automated release v$VERSION"
        git push origin "v$VERSION"
        
        echo "Modules published with version: v$VERSION"
        echo "##vso[task.setvariable variable=PublishedVersion]v$VERSION"
      displayName: 'Publish Modules'
      env:
        TF_CLOUD_TOKEN: $(apiKey)