trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.6.0'

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Run Terraform Plan'
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: $(terraformVersion)

    - script: |
        echo "Initializing Terraform modules..."
        cd iac/terraform/aws
        terraform init
        cd ../azure
        terraform init
        cd ../../..
      displayName: 'Terraform Init'

    - script: |
        echo "Running Terraform plan for AWS..."
        cd iac/terraform/aws
        terraform plan
        cd ../azure
        echo "Running Terraform plan for Azure..."
        terraform plan
        cd ../../..
      displayName: 'Terraform Plan'

- stage: Test
  displayName: 'Lint and Security Scan'
  dependsOn: Plan
  jobs:
  - job: LintAndScan
    displayName: 'Code Quality and Security'
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: $(terraformVersion)

    - script: |
        pip install checkov tflint-wrapper
      displayName: 'Install Security Tools'

    - script: |
        echo "Running Terraform format check..."
        cd iac/terraform/aws
        terraform fmt -check
        terraform validate
        cd ../azure
        terraform fmt -check
        terraform validate
        cd ../../..
      displayName: 'Terraform Lint'

    - script: |
        echo "Running security scan with Checkov..."
        cd iac/terraform/aws
        checkov -f . --framework terraform
        cd ../azure
        checkov -f . --framework terraform
        cd ../../..
      displayName: 'Security Scan'

- stage: Release
  displayName: 'Release Modules'
  dependsOn: Test
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: PublishModules
    displayName: 'Publish to Terraform Registry'
    steps:
    - script: |
        echo "Publishing modules to Terraform Cloud..."
        echo "This would typically involve:"
        echo "1. Tagging the release"
        echo "2. Publishing to Terraform Registry"
        echo "3. Updating module versions"
        echo "Release process completed"
      displayName: 'Publish Modules'