trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - README.md
      - .github/*
      - .aws/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.6.0'
  shouldRun: $[or(contains(variables['Build.SourceVersionMessage'], '[ado]'), not(or(contains(variables['Build.SourceVersionMessage'], '[gh]'), contains(variables['Build.SourceVersionMessage'], '[aws]'))))]

stages:
- template: templates/stages/plan.yml
  parameters:
    condition: eq(variables.shouldRun, true)
    terraformVersion: $(terraformVersion)
    examplePaths: 
      - 'examples/azure-example'
      - 'examples/aws-example'

- template: templates/stages/test.yml
  parameters:
    terraformVersion: $(terraformVersion)
    modulePaths:
      - 'iac/terraform/aws'
      - 'iac/terraform/azure'

- template: templates/stages/release.yml
  parameters:
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))